# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8031f672c8fdfbbf69f2093f73927fd8e61a9879d48d0e8006bd37b44ff583ce460bfe4f7d6c225204ff567583bd1c03cd6c3a3dc2ecdd0d780869bebdcf116b

test:
  secret_key_base: e769cc00af3f76ea59ed0605f4d627bf8e736d33cc4cdcf2cadeeae1dcf34d0f7e2cd052faa02c5f836767827c239dd735fc1647ca1ca9587ab8472804aab5e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
